#!/usr/bin/env bash
#
# Builds a release APK for the teleprompter app and optionally installs it.
#
# Why this script exists
# ----------------------
# `android/` is generated by `expo prebuild` and gitignored, so the environment
# fixes below are lost every time it is regenerated. Without them the build
# stalls: macOS routes the JVM through the system HTTP proxy, which hangs on
# overseas Maven repositories, and gradle.org itself is throttled to ~60 KB/s.
#
#   ./scripts/android-release.sh            # build + install to the connected device
#   ./scripts/android-release.sh --build    # build only
#   ABIS=arm64-v8a,x86_64 ./scripts/android-release.sh
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID_DIR="$ROOT_DIR/android"
APK_PATH="$ANDROID_DIR/app/build/outputs/apk/release/app-release.apk"
ABIS="${ABIS:-arm64-v8a}"
INSTALL=1

for arg in "$@"; do
  case "$arg" in
    --build) INSTALL=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

if [ ! -d "$ANDROID_DIR" ]; then
  echo "==> android/ missing, running expo prebuild"
  (cd "$ROOT_DIR" && npx expo prebuild --platform android --no-install)
fi

# Android SDK location, if it was not created by a previous run.
if [ ! -f "$ANDROID_DIR/local.properties" ]; then
  SDK_DIR="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-}}"
  if [ -z "$SDK_DIR" ]; then
    echo "ANDROID_HOME is not set" >&2
    exit 1
  fi
  printf 'sdk.dir=%s\n' "$SDK_DIR" > "$ANDROID_DIR/local.properties"
  echo "==> wrote local.properties (sdk.dir=$SDK_DIR)"
fi

# Mirror repositories. Passed with -I so nothing has to be injected into the
# generated build files.
cat > "$ANDROID_DIR/mirror.init.gradle" <<'GRADLE'
// Route dependency resolution through China-accessible mirrors FIRST, keeping
// the official repositories afterwards as a fallback.
def ALIYUN_GOOGLE = 'https://maven.aliyun.com/repository/google'
def ALIYUN_PUBLIC = 'https://maven.aliyun.com/repository/public'
def ALIYUN_PLUGIN = 'https://maven.aliyun.com/repository/gradle-plugin'

// Runs at project creation, i.e. before the project's own build script appends
// google()/mavenCentral(), so a plain append lands the mirrors first.
allprojects { project ->
  def addMirrors = { handler, urls ->
    def present = [] as Set
    handler.each { repo -> if (repo.hasProperty('url')) present << repo.url.toString() }
    urls.each { u -> if (!present.contains(u)) handler.maven { it.url = u } }
  }
  addMirrors(project.buildscript.repositories, [ALIYUN_PLUGIN, ALIYUN_GOOGLE, ALIYUN_PUBLIC])
  addMirrors(project.repositories, [ALIYUN_PUBLIC, ALIYUN_GOOGLE])
}

// pluginManagement is settings-scoped, so it is not covered by `allprojects`.
settingsEvaluated { settings ->
  def repoHandler = settings.pluginManagement.repositories
  def hadPortal = false
  def explicit = []
  def seen = [] as Set
  repoHandler.each { repo ->
    if (repo instanceof org.gradle.api.artifacts.repositories.MavenArtifactRepository) {
      def url = repo.url.toString()
      if (url.contains('plugins.gradle.org')) { hadPortal = true }
      else if (seen.add(url)) { explicit << url }
    }
  }
  repoHandler.clear()
  repoHandler.maven { it.url = ALIYUN_PLUGIN }
  repoHandler.maven { it.url = ALIYUN_GOOGLE }
  repoHandler.maven { it.url = ALIYUN_PUBLIC }
  explicit.each { u -> repoHandler.maven { it.url = u } }
  if (hadPortal || explicit.isEmpty()) { repoHandler.gradlePluginPortal() }
}
GRADLE

# Keep the Gradle daemon off the macOS system proxy, which hangs on overseas
# hosts, and give it enough heap for the native (CMake) builds.
if ! grep -q 'useSystemProxies=false' "$ANDROID_DIR/gradle.properties"; then
  python3 - "$ANDROID_DIR/gradle.properties" <<'PY'
import re, sys
path = sys.argv[1]
text = open(path).read()
line = "org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Djava.net.useSystemProxies=false"
if re.search(r'^org\.gradle\.jvmargs=.*$', text, re.M):
    text = re.sub(r'^org\.gradle\.jvmargs=.*$', line, text, flags=re.M)
else:
    text += f"\n{line}\n"
open(path, "w").write(text)
PY
  echo "==> patched gradle.properties (heap + direct network)"
fi

echo "==> assembling release ($ABIS)"
cd "$ANDROID_DIR"
./gradlew assembleRelease \
  -PreactNativeArchitectures="$ABIS" \
  -PsherpaOnnxDisableFfmpeg=true \
  -PsherpaOnnxDisableLibarchive=true \
  -I mirror.init.gradle \
  --console=plain

echo "==> built $(du -h "$APK_PATH" | cut -f1) -> $APK_PATH"

if [ "$INSTALL" -eq 1 ]; then
  if ! adb get-state >/dev/null 2>&1; then
    echo "no device connected; skipping install" >&2
    exit 0
  fi
  adb install -r "$APK_PATH"
  echo "==> installed"
fi
